### PR TITLE
Added basic structure files

### LINKED ISSUE #1: Set up structure
### Solution proposal
- [x] Create a ```index.html``` file

- [x]  Create ```css/main.css```

- [x] Create ```js/main.js```

### PR DESCRIPTION
**Pull request by te4-david-jensen**
Resolves #1

### CODE REVIEW

**Review by te4-andre-skvarc — APPROVED** [review]
Good, start!

**Review by te4-adrian-almetun-smeds — CHANGES_REQUESTED** [review]
Can this folder be renamed to public to prepare for a sinatra backend?

**Review by te4-adrian-almetun-smeds — APPROVED** [review]
:+1: On that change.

**Review by te4-andre-skvarc — APPROVED** [review]
Feels better now!

**Pull request merged**
